server:
  port: 8083

spring:
  application:
    name: ride-service
  datasource:
    url: jdbc:h2:file:./data/ridedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  services:
    driver-service-url: http://localhost:8082
    fare-service-url: http://localhost:8084

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
